### ISSUE TITLE
Multi-Architecture Docker Builds

### ISSUE THREAD

**Issue by rblaine95** [danubetech/workflows#7]
An imperfect example:
```yaml
jobs:
  build-image:
    name: Build and Cache Docker Image
    runs-on: ${{ matrix.runs-on }}
    permissions:
      contents: read

    strategy:
      fail-fast: false
      matrix:
        arch: ["amd64", "arm64"]
        include:
          - arch: amd64
            runs-on: ubuntu-24.04
          - arch: arm64
            runs-on: ubuntu-24.04-arm

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          install: true
          # buildx version mismatch between `ubuntu-24.04` and `ubuntu-24.04-arm`
          # means we have to ensure the latest version of buildx is installed
          version: latest

      - name: Build and Cache Image
        uses: docker/build-push-action@v6
        with:
          push: false
          context: .
          file: ${{ inputs.PATH_TO_DOCKERFILE }}
          build-args: |
            DANUBETECH_MAVEN_INTERNAL_USERNAME=${{ env.MAVEN_USERNAME }}
            DANUBETECH_MAVEN_INTERNAL_PASSWORD=${{ env.MAVEN_PASSWORD }}
          cache-from: type=gha,scope=docker-build-${{ matrix.arch }}
          cache-to: type=gha,scope=docker-build-${{ matrix.arch }},mode=max
          platforms: linux/${{ matrix.arch }}

  publish-images:
    name: Publish Docker Image
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    needs: build-image

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          install: true
          version: latest

      - name: Log in to the GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ github.token }}

      - name: Setup Image Metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ghcr.io/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}
          tags: |
            type=raw,latest

      - name: Publish Image to GHCR.io
        uses: docker/build-push-action@v6
        with:
          push: true
          context: .
          file: ${{ inputs.PATH_TO_DOCKERFILE }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            DANUBETECH_MAVEN_INTERNAL_USERNAME=${{ env.MAVEN_USERNAME }}
            DANUBETECH_MAVEN_INTERNAL_PASSWORD=${{ env.MAVEN_PASSWORD }}
          cache-from: |
            type=gha,scope=docker-build-arm64
            type=gha,scope=docker-build-amd64
          platforms: linux/amd64,linux/arm64
```

* Build `amd64` on `amd64` runner (`ubuntu-24.04`)
* Build `arm64` on `arm64` runner (`ubuntu-24.04-arm`)
* Cache, don't push anything
* Combine both architectures into a single Docker Image Manifest and push to GHCR.io (as an example)
